all: -r features --tags=~@upcoming --tags=~@encoding --format pretty --format rerun --out tmp/rerun.txt
default: -r features --tags=~@upcoming --tags=~@encoding --format pretty --format rerun --out tmp/rerun.txt
rerun: "-r features @tmp/rerun.txt --format pretty --format junit --out tmp/junit --format rerun --out tmp/rererun.txt"
profiling: -r features --tags=~@encoding --no-color  --format pretty --format usage --out tmp/cucumber_usage.txt --format rerun --out tmp/rerun.txt
encoding: --tags=@encoding
